### ISSUE TITLE
Windows version for SKD 0.3 whl

### ISSUE THREAD

**Issue by olavoholanda** [getchui/offline_sdk#1]
Hey guys, 

Can you build a wheel for windows_64 of the offline SDK version 0.3?

Thanks

**Comment by nchafni** [comment]
@olavoholanda Sounds good we'll add a wheel for windows for 0.3.

**Comment by olavoholanda** [comment]
Thanks!

**Comment by seelaman** [comment]
The wheel was added to the release page [here](https://github.com/getchui/offline_sdk/releases/tag/0.3)
